sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        jDKUc5opdKfig7V9TmfO0f1qYavTd/8XePP/iTuhMzQa4Anui70AaEHoGVISYXCA6HauXtTNPhWteWZQHBF4tGZZAFWdhEGFwT+8L7HgItg7YVz3IN3QK5FgtUm8FSoCl4jlf+hPjjrs1+s9Vz1vbJGZHKvdFnJIRLQ6Z0GxV9VbXxQu9TV3k/B83aBouusV8zYIs7UTCWbjuIDSQ6OwHC8PY3luVivS0Sgcda7YLEpMauN5HV6ci6iEL0oLc/4D3tHKr/uB9hKZaekcbrTVNKNkgpt7KSYoYJGNcmQbZIwOZXfm6KgNG7rhsFoKBpIH1TodxihSkCz66b2APTmaZK2/c1D3tDQLoLlhnzy1e2SX4S9T/Qzk9tDUX15aqHEyjnXvKJv31x1hhSU4ItO+01AHKgI+4wle6jKAbn3lKurIBjV53QbF1S5SnWxfHE9cJg1MM2yd6u+V8dRXCWCeoAsHidm9SmQ2n/8d82twtGLJNARdUpyAwkilfRtYOoD130vd0he0jl4Bt6VidH2O/qL6mGoNeErNMVKaGXLQ4iEY7k3Gu0h6Dm74scA8YK41C7Sln+alR5hluF0x1IvE6INO0zpXpaIUP/Sd9CxoT4BMcRHsYfwnyeGp+mGrPppZWYwFa4oMPnOkwY44VWG+4dgLUuU4VeXNq2NXiuvaDQA=
    - secure: >-
        coLdCY2EP+b5eBgNeu58gRvB7h2EepkAO0xDU6vXSjzlmQSWnPWDa2t+N+LOyG8+j0gFLpcdfogyspidyjlw4PEx0/9qMgKjGXJ3yL6W/jCdxawxuiEVksm5g4MIgbiViAS8LmxN844qBJLtfcotofs8Iz5P6j/WyFt6+SEaUSdtB1vy31g0jtOsBESOkspZGE/+rSg5dAsSQpkLOH4rXWJHKVIqAF5jAukoX14CuQL+JHEG8GcKRAw11g3smU65t2uJqCey4DIcggmx/tmYOHxWAE1lOfpgep/mlepCVmtU3WBiNF6Wu5rqjeBg4J6duhybD0IASQ4hg0kUwhVdFJdr7SNHid/QoSarJvnDpcqwUIWOIVkFHq+HpQYtLbzaXh1ivFQYYDa9loGVaG0A2Yl9ulVE4PratHJUk4T2dttSVEMqHMPtukGVfyQOean9iFeA30W6OfmAKMJu7DMl+eiGYOwAQnnwkfoN8mPMZTBvy7ukKJmqR7W1wVD8WQGHdJ9QWp6Sxt8doan6a3Hqu4btciLSTylw6OKOfjnTs15BHGeVz38s0U0GKoKOP2z3XVgtcQd1BqSD7vVMHzbyIJni3IytERqB5f6IcvZcVJv2ZOUMdREAU1ZWxZp9aP6A67qxH8ZE3Bogv+tMOwHCc/dQmERC5qVL4+p5NFh5IhA=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
